spring:
  main:
    banner-mode: off

  application:
    name: "insightfinder-gateway"

insightfinder:
  url: "https://ai-stg.insightfinder.com"

# OpenTelemetry configuration
otel:
  service:
    name: "insightfinder-gateway"
  exporter:
    otlp:
      endpoint: "http://localhost:4318"
  metrics:
    exporter: none
  logs:
    exporter: none