services:
  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.9.0
    container_name: jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "5778:5778"
      - "9411:9411"
    restart: unless-stopped

  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock-server
    restart: unless-stopped
    ports:
      - "8888:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/__files:/home/wiremock/__files
    command: [ "--global-response-templating", "--verbose" ]